troubleshooting

diff --git a/.github/workflows/Azuredeployinfra.yml b/.github/workflows/Azuredeployinfra.yml
--- a/.github/workflows/Azuredeployinfra.yml
+++ b/.github/workflows/Azuredeployinfra.yml
@@ -51,6 +51,12 @@ jobs:
       run: terraform fmt
       working-directory: ./terraform
 
+    - name: Terraform Validate
+      id: validate
+      # Run even if formatting fails
+      if: success() || failure()
+      run: terraform validate -no-color
+
     - name: Terraform Plan
       run: |
         export ARM_CLIENT_ID=$ARM_CLIENT_ID
@@ -64,6 +70,7 @@ jobs:
         ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
         ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
         ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
+        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
                   
     - name: Terraform Apply
       run: |
